#pragma once

#include "Component.h"

#include "AnimatorComponent.h"
#include "AudioListenerComponent.h"
#include "AudioSourceComponent.h"
#include "CameraComponent.h"
#include "CanvasComponent.h"
#include "DestroyComponent.h"
#include "DirtyComponent.h"
#include "EnabledComponent.h"
#include "MeshComponent.h"
#include "NameComponent.h"
#include "RelationshipComponent.h"
#include "RenderableComponent.h"
#include "ScriptComponent.h"
#include "ScriptEventComponent.h"
#include "ScriptObjectComponent.h"
#include "SpriteComponent.h"
#include "TagComponent.h"
#include "TextComponent.h"
#include "TransformComponent.h"
#include "UITransformComponent.h"