: 279e2c5cb4625c3c
push: object
    stageFlags: VERTEX_BIT
    offset: 0
    size: 64
uniform: camera
    type: UNIFORM_BUFFER
    stageFlags: VERTEX_BIT
    set: 0
    binding: 0
    size: 64
uniform: material
    type: UNIFORM_BUFFER
    stageFlags: VERTEX_BIT
    set: 2
    binding: 0
    size: 32
uniform: textures
    type: COMBINED_IMAGE_SAMPLER
    stageFlags: FRAGMENT_BIT
    set: 2
    binding: 1
    size: 8
    count: 4